// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/3/28 下午2:37:28
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/unikyolanda/fromislandtoisland/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/unikyolanda/fromislandtoisland/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/unikyolanda/fromislandtoisland/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/unikyolanda/fromislandtoisland/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/unikyolanda/fromislandtoisland/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/unikyolanda/fromislandtoisland/plugins/**/*.{js,ts,mjs}","/Users/unikyolanda/fromislandtoisland/composables/**/*.{js,ts,mjs}","/Users/unikyolanda/fromislandtoisland/utils/**/*.{js,ts,mjs}","/Users/unikyolanda/fromislandtoisland/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/unikyolanda/fromislandtoisland/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/unikyolanda/fromislandtoisland/app.config.{js,ts,mjs}","/Users/unikyolanda/fromislandtoisland/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;